[package]
name = "trebuchet-bencode"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9"
nom = { version = "7.0", features = ["alloc"] }
num-traits = "0.2"
itertools = "0.10"
